
=== RUNNING rnn =============

0
Created ../checkpoints directory
Created ../checkpoints/vocab directory
Created ../checkpoints/bpe directory
Created ../loss_plots directory
Created ../data/train directory
2024-10-27 13:12:34.940 | INFO     | __main__:<module>:22 - This is a debug message
Traceback (most recent call last):
  File "/home/hlp179/nlp/aske/bilstm/runscripts/run_bilstm.py", line 24, in <module>
    train_data = get_data_dic(language)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hlp179/nlp/aske/bilstm/runscripts/../utils/nlp_utils.py", line 140, in get_data_dic
    with open(filepath, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../data/train/edited_ds_fi.json'
... done <3
